name: Build and Deploy on GH Pages
on:
  push:
    branches:
      - master
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Git config
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
      - name: Prepare public
        run: git subtree add --prefix public origin gh-pages
      - name: Install
        run: npm i
      - name: Build
        run: npm run build
      - name: Push
        run: |
          git add -A -f public && git commit -m "Build and deploy on gh-pages"
          git subtree push --prefix public origin gh-pages
