name: Build and Deploy
on:
  push:
    branches:
      - dev
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Git config
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git checkout dev
      - name: Prepare public
        run: |
          git subtree add --prefix public origin master
          mv public/README.md ./README-temp.md
          rm -rf public/*
          mv ./README-temp.md public/README.md
      - name: Install
        run: npm i
      - name: Build
        run: npm run build
      - name: Push
        run: |
          git add -A -f public && git commit -m "Build and deploy"
          git subtree push --prefix public origin master
